# Site settings
title: "Nikolaos Anastasiou CV"
description: ""

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Nikolaos Anastasiou"
resume_title:                   "Surveying and Geoinfomatics Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "nikolas619065@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(+30)6945692088"
resume_contact_address:         "test adress"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: |
                    <div style="text-align: justify;">
                      <p>
                        I received my diploma in Rural, Surveying and Geoinformatics Engineering from the National Technical University of Athens in 2025.
                        My diploma thesis focused on the development and evaluation of deep learning models for wildfire spread prediction using remote sensing data.
                        I completed a three-month internship at the National Observatory of Athens, focusing on Earth observation and wildfire mapping. 
                        I am currently working at the Athena Research Center, where I am involved in training foundation models for fire detection from satellite data. 
                        My primary research interests include remote sensing and deep learning, with an emphasis on wildfire-related applications.
                      </p>

                      <p style="margin-top: 10px; text-align: center; font-size: 0.95em;">
                        📧 <a href="mailto:nikolas619065@gmail.com" style="color:#1a73e8;">nikolas619065@gmail.com</a> &nbsp; | &nbsp; 
                        📞 <a href="tel:+306945692088" style="color:#1a73e8;">(+30) 6945692088</a>
                      </p>
                    </div>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "false"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/nikos230"
  # resume_twitter_url:           ""
  # resume_dribbble_url:          ""
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/nikos-anastasiou/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://nikos230.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
